services:
  - type: web
    name: google-sheet-sync-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true

    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false  # secure
      - key: CONFIG_SHEET_URL
        sync: false
